### ISSUE TITLE
Dependency Resolution Failure: Unable to Install Specific Tensorflow Version

### ISSUE THREAD

**Issue by rohanrajput04** [BBischof/ESRecsys#3]
During the installation of project dependencies using pip install -r requirements.txt, the process fails when attempting to install Tensorflow version 2.9.1. The error message indicates that this specific version of Tensorflow is not available among the listed versions, which include 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, and 2.15.0rc1. It appears that Tensorflow 2.9.1 is either not hosted in the repository being used or there is an issue with version compatibility.

This issue prevents the successful setup of the project environment and may affect other users trying to set up the project. Below is the console output for reference:

`pip install -r requirements.txt
Collecting absl-py==1.1.0
  Using cached absl_py-1.1.0-py3-none-any.whl (123 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow==2.9.1 (from versions: 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0)
ERROR: No matching distribution found for tensorflow==2.9.1
`

Possible actions to resolve this issue could include updating the requirements.txt to use a version of Tensorflow that is available in the repository, or providing guidance on alternative ways to install Tensorflow 2.9.1, if that specific version is crucial for the project.

**Comment by hectorgon** [comment]
Hi Rohan I fixed the pinterest requirements.txt by pointing to the wheel, will fix the others

**Comment by rohanrajput04** [comment]
Thanks @hectorgon , however, it is still not supported as this version has been discontinued. 
![image](https://github.com/BBischof/ESRecsys/assets/15249335/92ae13f3-90b5-42c6-8b38-adb94120d9a2)

**Comment by rohanrajput04** [comment]
Upgrading some packages help me resolve these errors 
Run `pip install --upgrade jax jaxlib flax optax chex wandb`
